apiVersion: v1
kind: Service
metadata:
  name: guestbook-http
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
<<<<<<< HEAD
    nodePort: 30081
=======
    nodePort: 30080
>>>>>>> e7b91b2a1df844cec283bced43bcd715b3be1164
  selector:
    app: guestbook
